---
- name: Change owner and access
  hosts: all
  tasks:
  - name: Change owner of Path
    win_owner:
      path: C:\Temp\test.conf
      user: xoaasatar
  - name: Add xoaasatar allow rights
    win_acl:
      path: C:\Temp\test.conf
      user: xoaasatar
      rights: FullControl
      type: allow
      state: present
      inherit: ContainerInherit, ObjectInherit
      propagation: 'None'
