---
- name: Testing firewall
  hosts: all
  tasks:
  - name: Deny port 80
    win_firewall_rule:
      name: Testing
      state: present
      enable: true
      localport: 80
      action: block
      direction: In
      protocol : TCP