---
- name: Installing windows updates
  hosts: all
  tasks:
  - name: Updating windows
    win_updates:
      category_name:
      - Updates
      - CriticalUpdates
      - SecurityUpdates
      - UpdateRollups
      - Guidance
      - DeveloperKits
      state: installed